name: ServerDefender
author: CapitainFoxy
main: com.capitainfoxy.serverdefender.Main
commands:
  kick:
    description: Kick
  ban:
    description: Bans 
  banip:
    description: Bans ip
  mute:
    description: Mute
  unmute:
    description: Unmute
  lockdown:
    description: Lockdown
  chatlockdown:
    description: Locks chat
  sdlockdown:
    description: nfnfn
  warn:
    description: Warn
  automod:
    description: Automod on
